### ISSUE TITLE
refactor save_config_to_disk() and load_config_to_runtime()

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.proxysql#68]
the functions `save_config_to_disc()` and `load_config_to_runtime()` are used in every module.   
better refactor them and move them also to `plugins/module_utils/mysql.py`

**Comment by Andersson007** [comment]
we could leave this issue for the hackathon https://hackmd.io/AcI9TZf_SZqi7NG3ZyplnA#Hackathon in the summit.
@markuman what do you think?

cc @dericcrago @Ompragash @gundalow this is a very straightforward refactoring that does not imply any knowledge of ProxySQL  (it's about getting rid of code duplication across the files by moving a function to a library and loading it everywhere instead of having a copy of the function in each file).

**Comment by Andersson007** [comment]
Added https://hackmd.io/CqUQNTEqRBCHBTC4WF-9Aw?view#Basic-collection-code-refactoring . Please don't fix this before the hackathon.

**Comment by Andersson007** [comment]
FYI: Started by Honiix on Matrix, don't pick it up!

**Comment by laurent-indermuehle** [comment]
Just for clarification, I'm Honiix.
